CREATE TABLE `logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(20) NOT NULL,
  `channel` VARCHAR(64) NOT NULL,
  `event` VARCHAR(128) NOT NULL,
  `message` TEXT NOT NULL,
  `context` JSON NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `subject_type` VARCHAR(255) NULL,
  `subject_id` BIGINT UNSIGNED NULL,
  `ip_address` VARCHAR(45) NULL,
  `request_id` CHAR(36) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `logs_level_index` (`level`),
  KEY `logs_channel_index` (`channel`),
  KEY `logs_event_index` (`event`),
  KEY `logs_user_id_foreign` (`user_id`),
  KEY `logs_subject_type_subject_id_index` (`subject_type`, `subject_id`),
  KEY `logs_request_id_index` (`request_id`),
  KEY `logs_created_at_index` (`created_at`),
  KEY `logs_channel_created_at_index` (`channel`, `created_at`),
  KEY `logs_level_created_at_index` (`level`, `created_at`),
  CONSTRAINT `logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
